name: carton_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - images/carlos.png
    - images/lucia.png
    - images/pedro.png
    - images/ana.png
    - images/miguel.png
    - images/carla.png
    - images/andres.png
    - images/patricia.png
    - images/jorge.png
    - images/elena.png
