// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPliWHISkItJ53Jq5CYg8JJkVpawvYxeo',
    appId: '1:131586091441:web:2a94e189e6e766a608f590',
    messagingSenderId: '131586091441',
    projectId: 'practica-firebase-1b4da',
    authDomain: 'practica-firebase-1b4da.firebaseapp.com',
    storageBucket: 'practica-firebase-1b4da.firebasestorage.app',
    measurementId: 'G-4XXBZ6L63E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKlrNtuGWwDqoTDWsMe6jQ_uP2GwHjZO8',
    appId: '1:131586091441:android:36efe30dd0dadb0908f590',
    messagingSenderId: '131586091441',
    projectId: 'practica-firebase-1b4da',
    storageBucket: 'practica-firebase-1b4da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5pMjJR0Fklu5kHoqckxfS1qJdj09zBHU',
    appId: '1:131586091441:ios:1147d482d60c7e2f08f590',
    messagingSenderId: '131586091441',
    projectId: 'practica-firebase-1b4da',
    storageBucket: 'practica-firebase-1b4da.firebasestorage.app',
    iosBundleId: 'com.example.practicaFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5pMjJR0Fklu5kHoqckxfS1qJdj09zBHU',
    appId: '1:131586091441:ios:1147d482d60c7e2f08f590',
    messagingSenderId: '131586091441',
    projectId: 'practica-firebase-1b4da',
    storageBucket: 'practica-firebase-1b4da.firebasestorage.app',
    iosBundleId: 'com.example.practicaFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPliWHISkItJ53Jq5CYg8JJkVpawvYxeo',
    appId: '1:131586091441:web:0222e50ab294bd5108f590',
    messagingSenderId: '131586091441',
    projectId: 'practica-firebase-1b4da',
    authDomain: 'practica-firebase-1b4da.firebaseapp.com',
    storageBucket: 'practica-firebase-1b4da.firebasestorage.app',
    measurementId: 'G-W7TBCHVK2R',
  );
}
